# You can generate it here: https://github.com/settings/tokens
# Guest OS timezone
timezone: UTC
# Are we need check box updates for every 'vagrant up'?
box_check_update: true
# Virtual machine name
machine_name: engine.devel
# Virtual machine IP
ip: 192.168.66.66
# Virtual machine CPU cores number
cpus: 1
# Virtual machine RAM
memory: 2048
